"use client";

import { SERVICES, whatsappUrl } from "@/lib/constants";
import { CTAButton } from "@/components/ui/CTAButton";
import { GlassCard } from "@/components/ui/GlassCard";
import { ScrollReveal } from "@/components/ui/ScrollReveal";
import { SectionHeading } from "@/components/ui/SectionHeading";

function ServiceVisual({ index }: { index: number }) {
  if (index === 0) return <div className="mx-auto aspect-[9/16] w-32 rounded-[24px] border border-white/12 bg-[linear-gradient(145deg,#261d10,#0f0e0c)] p-2 shadow-2xl"><div className="grid h-full place-items-center rounded-[18px] border border-white/8 bg-[radial-gradient(circle_at_50%_30%,rgba(212,168,83,.18),transparent_55%)]"><span className="grid h-12 w-12 place-items-center rounded-full border border-white/10 bg-white/[.04] text-xl text-[#d4a853]">▶</span></div></div>;
  if (index === 1) return <div className="mx-auto w-full max-w-sm overflow-hidden rounded-xl border border-white/10 bg-[#100f0c]"><div className="flex h-8 items-center gap-1.5 border-b border-white/8 px-3"><i className="h-2 w-2 rounded-full bg-[#d4a853]/50"/><i className="h-2 w-2 rounded-full bg-white/15"/><i className="h-2 w-2 rounded-full bg-white/15"/></div><div className="aspect-[16/10] bg-[radial-gradient(circle_at_30%_20%,rgba(212,168,83,.18),transparent_35%),linear-gradient(160deg,#18140e,#080808)] p-5"><div className="h-2 w-1/3 bg-white/10"/><div className="mt-4 h-8 w-3/4 bg-[#f5f0e8]/10"/><div className="mt-2 h-8 w-1/2 bg-[#d4a853]/15"/></div></div>;
  if (index === 2) return <div className="flex h-48 items-center justify-center overflow-hidden px-6">{Array.from({ length: 5 }, (_, item) => <div key={item} className="-ml-5 aspect-[4/5] h-36 rounded-lg border border-white/10 bg-[linear-gradient(145deg,#2a1e10,#0d0c0a)] shadow-xl first:ml-0" style={{ transform: `rotate(${(item - 2) * 4}deg)` }} />)}</div>;
  return <div className="mx-auto max-w-md rounded-2xl border border-white/10 bg-[#11100d] p-5"><div className="flex items-start gap-4"><div className="grid h-12 w-12 place-items-center rounded-lg bg-[#d4a853]/15 text-[#d4a853]">RV</div><div><div className="font-semibold text-[#f5f0e8]">Negócio local</div><div className="mt-1 text-xs text-[#a89f8f]">Perfil da Empresa no Google</div><div className="mt-3 flex gap-1 text-[#d4a853]" aria-label="Representação visual ilustrativa">★★★★★</div></div></div><div className="mt-5 h-20 rounded-lg bg-[linear-gradient(135deg,#172016,#15110c)]"/></div>;
}

export default function Services() {
  return <section id="servicos" className="bg-[#12100c] px-6 py-20 md:px-12 md:py-28 xl:px-20 xl:py-[120px]"><div className="mx-auto max-w-[1280px]"><ScrollReveal><SectionHeading overline="A solução" title="UMA ESTRUTURA. UMA TRANSFORMAÇÃO. NO MESMO DIA." subtitle="Vídeo, site, anúncios e presença no Google — produzidos com IA, refinados por decisão humana e entregues em um único fluxo."/></ScrollReveal><div className="grid gap-6 lg:grid-cols-5">{SERVICES.map((service, index) => <ScrollReveal key={service.number} className={`${index === 0 ? "lg:col-span-3" : index === 1 ? "lg:col-span-2" : "lg:col-span-5"}`}><GlassCard className={`relative h-full overflow-hidden p-7 md:p-9 ${index > 1 ? "md:grid md:grid-cols-2 md:items-center md:gap-10" : ""}`}><span aria-hidden="true" className="pointer-events-none absolute -right-2 -top-5 font-display text-[clamp(4rem,8vw,8rem)] leading-none text-white/[.05]">{service.number}</span><div className="relative z-10"><span className="font-mono text-xs text-[#d4a853]">{service.number}</span><h3 className="mt-4 max-w-xl font-display text-[clamp(1.5rem,3vw,2.25rem)] leading-tight text-[#f5f0e8]">{service.title}</h3><p className="mt-4 max-w-xl text-sm leading-7 text-[#a89f8f] md:text-base">{service.description}</p><span className="mt-6 inline-block border border-[#d4a853]/20 px-3 py-2 text-xs text-[#d4a853]">{service.badge}</span></div><div className={`relative z-10 ${index < 2 ? "mt-9" : "mt-9 md:mt-0"}`}><ServiceVisual index={index}/></div></GlassCard></ScrollReveal>)}</div><ScrollReveal className="mt-10"><CTAButton href={whatsappUrl()} dataCta="whatsapp-solucao" section="solucao">Quero essa estrutura</CTAButton></ScrollReveal></div></section>;
}
