export const BRAND = {
  name: 'Rei das Vendas',
  tagline: 'Do primeiro clique à próxima venda, tudo precisa funcionar',
  subtitle: 'Sites, lojas, aplicativos e operações digitais construídos para negócios locais.',
  phone: '5516992333344',
  phoneDisplay: '(16) 99233-3344',
  whatsapp: 'https://wa.me/5516992333344?text=Ol%C3%A1!%20Quero%20mapear%20as%20oportunidades%20digitais%20do%20meu%20neg%C3%B3cio.',
  email: 'contato@reidasvendas.com.br',
  instagram: 'https://instagram.com/reidasvendas',
  linkedin: 'https://linkedin.com/company/reidasvendas',
  address: 'Franca, SP — Brasil',
  founder: {
    name: 'Thiago B. G. Piola',
    title: 'Fundador e diretor de projeto',
    site: 'https://thiagopiola.com.br',
    bio: 'Direção de produto e crescimento digital em Franca. Conecta presença, produto, aquisição e atendimento em projetos individuais para negócios locais.',
  },
  images: {
    hero: '/videos/hero-signal-loop.mp4',
    og: '/imagens/og-default.jpg',
    services: {
      sites: '/imagens/services/sites.jpg',
      apps: '/imagens/services/apps.jpg',
      automations: '/imagens/services/automations.jpg',
      dashboards: '/imagens/services/dashboards.jpg',
      mentoria: '/imagens/services/mentoria.jpg',
    },
    nichos: {
      calcadista: '/imagens/nichos/calcadista.jpg',
      comercio: '/imagens/nichos/comercio.jpg',
      industria: '/imagens/nichos/industria.jpg',
      saude: '/imagens/nichos/saude.jpg',
      educacao: '/imagens/nichos/educacao.jpg',
      servicos: '/imagens/nichos/servicos.jpg',
    },
  },
  seo: {
    title: 'Sites, aplicativos e soluções digitais em Franca | Rei das Vendas',
    description: 'Sites premium, e-commerce, aplicativos, SaaS, automações e operação digital sob medida para negócios locais e profissionais liberais em Franca, SP.',
    keywords: [
      'site profissional Franca SP',
      'criação de sites Franca',
      'desenvolvimento de aplicativos Franca',
      'ecommerce profissional Franca',
      'desenvolvimento SaaS Franca',
      'automação de WhatsApp Franca',
      'soluções digitais para negócios locais',
      'sites para negócios locais',
      'site para empresa Franca',
      'site que funciona no celular',
      'presença online para empresas locais',
      'site para prestador de serviço Franca',
      'Google Maps para empresa local',
    ],
    geo: {
      city: 'Franca',
      state: 'SP',
      country: 'BR',
      region: 'Região de Franca',
      areaServed: ['Franca', 'Região de Franca', 'Brasil'],
    },
  },
};
