export const BRAND = {
  name: 'Rei das Vendas',
  tagline: 'Da busca à venda, sem perder ninguém no caminho',
  subtitle: 'Sites que aparecem no Google, abrem rápido no celular e transformam visita em cliente.',
  phone: '5516993333344',
  whatsapp: 'https://wa.me/5516993333344?text=Ol%C3%A1!%20Quero%20uma%20an%C3%A1lise%20da%20presen%C3%A7a%20online%20da%20minha%20empresa.',
  email: 'contato@reidasvendas.com.br',
  instagram: 'https://instagram.com/reidasvendas',
  linkedin: 'https://linkedin.com/company/reidasvendas',
  address: 'Franca, SP — Brasil',
  founder: {
    name: 'Thiago B. G. Piola',
    title: 'Fundador e diretor de projeto',
    site: 'https://thiagopiola.com.br',
    bio: 'Web designer e estrategista digital de Franca. Monta sites que aparecem no Google, abrem rápido no celular e transformam visita em cliente.',
  },
  images: {
    hero: '/videos/hero-signal-loop.mp4',
    og: '/imagens/og-default.jpg',
    services: {
      sites: '/imagens/services/sites.jpg',
      apps: '/imagens/services/apps.jpg',
      automations: '/imagens/services/automations.jpg',
      dashboards: '/imagens/services/dashboards.jpg',
      mentoria: '/imagens/services/mentoria.jpg',
    },
    nichos: {
      calcadista: '/imagens/nichos/calcadista.jpg',
      comercio: '/imagens/nichos/comercio.jpg',
      industria: '/imagens/nichos/industria.jpg',
      saude: '/imagens/nichos/saude.jpg',
      educacao: '/imagens/nichos/educacao.jpg',
      servicos: '/imagens/nichos/servicos.jpg',
    },
  },
  seo: {
    title: 'Sites e sistemas para organizar a jornada de venda | Rei das Vendas',
    description: 'Mapeamento, arquitetura e implementação para negócios que precisam transformar busca, interesse e atendimento em um único fluxo comercial.',
    keywords: [
      'site profissional Franca SP',
      'criação de sites Franca',
      'sites para negócios locais',
      'site para empresa Franca',
      'site que funciona no celular',
      'presença online para empresas locais',
      'site para clínica Franca',
      'site para restaurante Franca',
      'site para prestador de serviço Franca',
      'Google Maps para empresa local',
    ],
    geo: {
      city: 'Franca',
      state: 'SP',
      country: 'BR',
      region: 'Região de Franca',
      areaServed: ['Franca', 'Região de Franca', 'Brasil'],
    },
  },
};
